buildscript {
    repositories {
        maven {
            url 'http://localhost:8080/snapshots'
        }

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}

plugins {
    id 'scala'
    id 'maven'
}

apply plugin: 'info.gianlucacosta.aurora'

group = 'info.gianlucacosta.helios'
archivesBaseName = 'helios-jpa'
version = '2.0.0-SNAPSHOT'

description = 'Scala library of JPA utilities'

dependencies {
    generatedCompile 'org.scala-lang:scala-library:2.13.14'

    compile 'org.scala-lang:scala-library:2.13.14'

    compile 'org.hibernate:hibernate-entitymanager:5.2.3.Final'
}

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    mavenDeploy {
        url = 'http://localhost:8080/snapshots'
    }
}
